sudo: false
language: php
matrix:
  fast_finish: true
  include:
    - php: 7.1
before_install:
  - openssl aes-256-cbc -K $encrypted_cbd724a3f1cf_key -iv $encrypted_cbd724a3f1cf_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
  - phpenv config-rm xdebug.ini
  - composer self-update
install:
  - travis_retry composer install --no-interaction --no-dev --optimize-autoloader --classmap-authoritative
  - composer info -i

after_success:
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev ; fi
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./bin/deploy.sh ; fi